const char* breakdancegif[] = {
"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                      +$++\n"
"                     ,JJJ%%\n"
"                       %**D+%D%Y\n"
"                       DDJDDDDD%%%\n"
"                       DJDDDJJJJJ++P$\n"
"                      %DDDDDDDDD% %*P*\n"
"                      JJDDD%DDDJY   DPP\n"
"                      $JJ%%%%%%%D    DP\n"
"                       %JJD%DD%DDD    *P,\n"
"                        DJJJ%DDYYY$$$  PP\n"
"                        PJ%%$+YYYY$$YY\n"
"                         YYY$$Y%*PY$$Y$\n"
"                        $YY$Y+Y%*%Y$$$Y$\n"
"                        Y$Y$Y*JJJJY$$Y**$\n"
"                       YYYYY+       P+PP+\n"
"                   YY+YDPYY$        +PYPP\n"
"                   YY$Y+$D+Y        JP+Y\n"
"                    YY++YYY$        P**\n"
"                      ,YYYYY       ,P+,\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                        ,Y++,\n"
"                       ,*JDDP\n"
"                        YD**%$,,$,\n"
"                         PDDD%%%%%Y\n"
"                         PJDDDDDDDDP,\n"
"                       ,*DDDDDDDJJ%P+$\n"
"                       ,DDDDDDDDDJPPP*Y\n"
"                        *J%%%%%%D% ,P%P$\n"
"                        $DD%DDDDD*   P*+,\n"
"                        ,%DD*%D%**$   +*Y\n"
"                       $P**+Y+PY$$Y,   +P$\n"
"                     ,,YY$$$Y++Y$$Y$   $*PY,\n"
"                    ,$YY$YY++*PY$$$$   ,+P*$\n"
"                  ,$YYYYY+**DJ%Y$$Y$     ,,\n"
"           ,,,   ,YYYYYYP*P%*++Y$$Y$,\n"
"          ,Y+Y$Y++Y$YY$,,,    $++++Y\n"
"          ,$YY++PPPYYY,      $PPP++Y\n"
"           ,YY++YY+P+,      ,+PPPP+,\n"
"             ,$YYYY+Y       YPPPP+,\n"
"                ,YYPY       +*PY,\n"
"                 ,,$,       ,$,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                        ,Y++,\n"
"                       ,*JDDP\n"
"                        YD**%$,,$,\n"
"                         PDDD%%%%%Y\n"
"                         PJDDDDDDDDP,\n"
"                       ,*DDDDDDDJJ%P+$\n"
"                       ,DDDDDDDDDJP+P*Y\n"
"                        *J%%%%%DD% ,P%P$\n"
"                        $DD%DDDDD*   P*+,\n"
"                        ,%DD*%D%**$   +*Y\n"
"                       $P**+Y+PY$$Y,   +P$\n"
"                     ,,YY$$$Y++Y$$Y$   $*PY,\n"
"                    ,$YY$YY++*PY$$$$   ,+P*$\n"
"                  ,$YYYYY+**DJ%Y$$Y$     ,,\n"
"           ,,,   ,YYYYYYP*P%*++Y$$Y$,\n"
"          ,Y+Y$Y++Y$YY$,,,    $++++$\n"
"          ,$YY++PPPYYY       $PPP++Y\n"
"           ,YY++YY+P+,      ,+PPPP+,\n"
"             ,$YYYY+Y       YPPPP+,\n"
"                ,YYPY       +*PY,\n"
"                 ,,$,       ,$,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                           ,$Y$\n"
"                          ,*DDDY\n"
"                           PD**P\n"
"                           ,%%%%+$,,\n"
"                           Y%JDDDD%*Y\n"
"                         $*DDDDDDDDDD+\n"
"                         +JDD%DDDDDD%%$\n"
"                         ,DD%%%%DDDDP+Y\n"
"                          %D%%%%%DDPY*P$\n"
"                       ,PP%D%%%%DD%, +%P,\n"
"                     ,,YP*P++%D%***  ,P*+,\n"
"                  ,,$$YY$$$Y+P+YYYY   ,PP$\n"
"                ,$$YYY$YY+P*P$$$YY,    ,*+\n"
"              ,$$$YY$Y+P%**%Y$$$Y$      +*$\n"
"      ,,    ,$YYYYYY$++Y$,,Y$$$Y$,      Y*PY,\n"
"     $++Y$$$$YYYYY$,     ,$$$$YY,       ,+**$\n"
"    ,YYY+*D*Y$YYY,      ,Y$$$YY,          ,,\n"
"     ,Y++++PPYY$,     ,YP*%+$$,\n"
"      ,$++Y$P*+,     ,+PPPDDY,\n"
"        ,$+++Y,    ,YPPP++Y$,\n"
"          $YY,     +*PPPP$\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                ,,\n"
"                              $P**Y\n"
"                              +JDD%,\n"
"                              $%**P\n"
"                             ,$%DD%Y$,\n"
"                           ,P%%DDDDDD%+\n"
"                           +JDD%DDDDDDDY\n"
"                           PJD%%%%DDDJD*\n"
"                        ,,,*D%%%%%DDDJD*$\n"
"                       ,P%%DD%%%%DDD%Y*PY\n"
"                    ,,$$+%%*PD%%DDD%$ +*+\n"
"                ,,$$YYY$$$YY*%%%%DD$  $*P$\n"
"              ,$$$YYY$YYY+P+YYYYYPY   ,P*Y\n"
"           ,,$$$Y$$YY+PPP*P$$$YYY$     $*+\n"
"         ,,YYY$YYYY+Y$$,,$$$YY++$,     ,P+\n"
" ,$$,  ,$$YY$YYY$,,   ,$$$$YYYY,        +*$\n"
" Y++PPPPYYYYYY$,    ,$$$$$Y+$,          $+P+,\n"
" $+++*%*+YY+$,    ,$Y$$$$Y+,              ,,\n"
"  $+*+YPP+P$  ,$+P+$$$Y$,,\n"
"    $PYY**$ ,$+%DDJ*YY$,\n"
"     ,YY$, ,PPP*JJPP+,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                   ,,\n"
"                                  P%%*,\n"
"                                 ,%DDJY\n"
"                                ,$%%**,\n"
"                             ,+*%%DDJ%Y,\n"
"                             *DDDDDDDDD%+\n"
"                            ,DJDD%%DDDDDDY\n"
"                         ,,,+DD%%%%%DDDJJ*\n"
"                        ,+%%DD%%%%%%DD*%D*,\n"
"                    ,,$$$Y*D%%%DD%%DD*,$%*$\n"
"                ,,$$Y$Y$$$YP+*DD%%DD*,  **Y\n"
"             ,,$$$YY$$YYY+P++*%%DDDP    +P+\n"
"           ,$$$$YYYYYY+PP*+$$$YYPPY     Y*+\n"
"        ,,$YY$YYYY$$,,,,$$$$$YYYY,      ,P+\n"
"      ,$$YY$$YYY$,  ,,$$$Y$Y+YY,         P+\n"
"Y+Y$YYYYYYYYY$,  ,,$$$$$YY++$,           +*+$\n"
"PP%DD*$YYY$,, ,$$$$$$$Y+YYY,              ,$$\n"
"YP****++YYYPY$$$$$$$Y++$,\n"
" ,YYY**PP%DD*$$$Y$$Y$,\n"
"    ,Y+*DDJJDYYY$,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                    ,$,,,\n"
"                                   ,*D%%+\n"
"                                   ,D%%D+\n"
"                               ,$YYPD%*%$\n"
"                              $%DDDDDDJJP,\n"
"                              *JDDDDDDDDD%+\n"
"                             $DJDD%%%%DDDD%,\n"
"                         ,,+P*DD%%%%%%DDJJD$\n"
"                      ,,$YYY%DDDDD%%%%D*PD%$\n"
"                  ,,$$$$$$$$PD*%DDDDDD*,,%%$\n"
"              ,,$$$$$$$$$$$YYYY*D%DDDP, ,**Y\n"
"           ,,$$$$YYYYYYY+PP+Y$*DDDDD*,  ,P*Y\n"
"        ,,$YYYYYYYYYY$,,$Y$$YYY+*%%+,    +*Y\n"
"     ,,$$YYYYYYY$,,,,,$$$$$$$YY+YY,      $*$\n"
"   ,$$YYYYYYY$,,,,$$$Y$$$YYY+YY$         $*+,,\n"
"YP*%D+YPP+$$,$$$$$$$YYY+P+YY,,           ,Y+P$\n"
"+*DD%%P%DP$$$$$$$$Y++Y+Y$,\n"
" ,YP*%DDD+YYY$$$$,,,,\n"
"  ,PDJJJ%+YY$,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                    ,$,,,\n"
"                                   ,*D%%+\n"
"                                   ,D%%D+\n"
"                               ,$YYPD%*%$\n"
"                              $%DDDDDDJJP,\n"
"                              *JDDDDDDDDD%+\n"
"                             $DJDD%%%%DDDD%,\n"
"                         ,,+P*DD%%%%%%DDJJD$\n"
"                      ,,$YYY%DDDDD%%%%D*PD%$\n"
"                  ,,$$$$$$$$PD*%DDDDDD*,,%%$\n"
"              ,,$$$$$$$$$$$YYYY*D%DDDP, ,**Y\n"
"           ,,$$$$YYYYYYY+PP+Y$*DDDDD*,  ,P*Y\n"
"        ,,$YYYYYYYYYY$,,$Y$$$YY+*%%+,    +*Y\n"
"     ,,$$YYYYYYY$,,,,,$$$$$$$YY+YY,      $*$\n"
"   ,$$YYYYYYY$,,,,$$$Y$$$YYY+YY$         $*+,,\n"
"YP*%D+YPP+$$,$$$$$$$YYY+P+YY,,           ,Y+P$\n"
"+*DD%%P%DP$$$$$$$$Y++Y+Y$,\n"
" ,YP*%DDD+YYY$$$$,,,,\n"
"  ,PDJJJ%+YY$,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                       ,\n"
"                                     $+YY,\n"
"                                     *JDD*\n"
"                                   ,$D%%%P\n"
"                               ,+**%DDD%D+\n"
"                               PJDDDDDDDJD+\n"
"                              $DJJDDDDDDDDD+\n"
"                            ,Y%DDDD%%%DDDDDD,\n"
"                         ,,$+%DDDD%%%%%DDJJ*\n"
"                      ,,,$YY$PDDDDD%%%%DP*JP\n"
"                ,,,,$$$$$$$$$PDDDDDDDDDP +%P\n"
"           ,,$$$$$$$$Y$$$$$YYYY+%DDDDJP  Y*P,\n"
"        ,,$$YYYYYYYYYYY$YYY+YY$Y%DDDJP   $*+\n"
"     ,$$$YYY+YYYY$$,$$$$$$$$YYYPDDDD*,   ,P+\n"
"   $+YYYY+P+Y$,,,,,$$$$$$$$$YYYYYY$,,    ,P+,\n"
" Y*DD%P*%*YY$$$$$YYY$$YYYY+++Y$,          YPPY,\n"
",*D%*%%D%Y$$$YYYYY+++PP+YY$,,              ,,,\n"
" ,+*%JDJ*Y++Y$$$,,$$$,,\n"
"   $PPY$,,,,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                      ,,,,\n"
"                                     ,PP++$\n"
"                                     YJJDDP\n"
"                                 $++Y*D%%%$\n"
"                               ,PDDDDDDD%%$\n"
"                              ,PJJDDDDDDDD%+\n"
"                             $PDDDDDDDDDDDDDY\n"
"                            YP*%%%DDD%DDDDDDY\n"
"                          ,YP%D%DDDD%%%%DDJD,\n"
"                       ,,$Y$$+DDDDDD%%%D*+J%,\n"
"            ,,,,,,,,$$$$$YYY$Y%DDDDDDDD*,$*P,\n"
"       ,,,$$$$$$Y$$$YYY$YYYY$YPDDDDDDJ%, $*P,\n"
"     ,$YYYYY+++++++YY++++++YYYY+*DDDJ%,  ,*+\n"
"   $P%%+$$$Y+PPPPP+++YYY$$YYYY$$*DDD*,   ,P+\n"
"  ,%D%%P++$$$YYYYYY$$$$$$$$YYYYY++Y$,     +*+$,\n"
"  ,P%*DDJ+YYYYYYYYYYYY+++++++Y$,          ,$YY,\n"
"    Y*%*PYY+++PPP*PPP+Y$$,,,\n"
"     ,,      ,,,,,,,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                      ,$Y$,\n"
"                                      +P++Y\n"
"                                     $DJJJ*,\n"
"                                 Y***%JD%%+\n"
"                               ,*JDDDDDDDD*,\n"
"                            ,$+%JJDDDDDDDDD*,\n"
"                           ,+*%*YPJDDDD%DDDDP\n"
"                         ,YP*P$,P%DDDDDDDDDDY\n"
"                       $Y+P+Y+P%DDDDD%%DDDJD,\n"
"                      ,PP+$$$*JDDDDDD%%D%PD*,\n"
"         ,,$$$$$$$$$$$$Y$YYYYYDDDDDDDDD%$$%P,\n"
"        $YYYYYYYYYYYYYYYYYYY$$%JDDDDDJ%, ,*+\n"
"      $*%+++++PPPP+++++P+++++YP*DDDDD*,   P+\n"
"     ,P%%+$$Y+++++++YYYYYYYYYYYY*DD%Y     +*+$\n"
"     ,%DDDP+YYYYYYYYYYYYYYYYY+YY$$,,      ,Y+Y,\n"
"     ,+PY$$YYY+++++++++++P+Y$$$,\n"
"               ,,,,,,,,,,,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                        ,\n"
"                                      ,Y+Y$\n"
"                                      +P+Y+,\n"
"                                  ,,,,DDDD*\n"
"                                Y*D%%%JDDDP\n"
"                            ,$Y*JJDDDDJJ%%%,\n"
"                           $+P%%*%DDDDDDJJD%+\n"
"                         ,+***+, *JDDDD%%DDD%,\n"
"                     $+PPPPY$,,$*DDDDDDDDDDDY\n"
"                     YYP+$,,+*%DDDDDDDDDDDD%,\n"
"            ,,,,,,,, ,,$$YY$+DDDDDDDDDDD%PD*,\n"
"         ,$$YYYYYY$$$$YYY+YYYPJJJJDDDDD*,,%+\n"
"       ,+%%*P+++++YYYYYYYYYY$YDJDJDDJJ*,  P+\n"
"      ,+%%%+YYY++++++++++++++Y*DDDJJD+,   P*Y,\n"
"      $DDD%YYYYYYYYYYYYYYYYY+Y+PDDJJ+     $+P+,\n"
"      ,YY$,$$YYYYYYYY+YY+++YYYYY*D*+,\n"
"                 ,,,,,,,,,,,,,   $,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                      ,++Y$\n"
"                                      PPYY+,\n"
"                                 ,,,,YD%***Y\n"
"                             ,$+*%D%%DJJJJ%,\n"
"                           ,+*%DJJDDDJJJ%%%Y\n"
"                          YP*%P+PDDDDDJJJDDD+\n"
"                         Y*P+,  $JJDDDDDDDDD*\n"
"                     ,$YP*P,,$$+DJJDDDDDDDD*,\n"
"                ,,,,,+P***+Y%DJDDDDDDDDDDDDP\n"
"         Y+PYYY$YYY$Y++*%P$$*DDJDDDDDDDJ*PD+\n"
"        ,%%DP+Y+++++P*%%*++Y+DJJJJDDDDDP ,%Y\n"
"       $*%DPY$$Y++++*%**+++YY*JJJJJJJJY  ,*PY,\n"
"       +D%%+P++++YY+P++YYY+++PDDDJJJDY    Y+PY\n"
"       ,,, ,,$$Y$YYYYYYY++++YYP*DD%P,\n"
"                     ,,,,,,,,, ,$+,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                      ,++Y,\n"
"                                     ,PP+Y+,\n"
"                                     Y*P+Y+Y\n"
"                            ,$YP*P*P*DJ%%%*$\n"
"                           Y*%%JJDDDDJJJJDDP,\n"
"                          +*%*PDJJDDDJJJDDDDP\n"
"                         YP*+,,$DJDDDDJJJJDD+\n"
"          ,YY$,,,,,,,,$$Y**%%DDDJJJDDDDDDDDP\n"
"          $%D*YY++YYYYYYP**+DDJJJJJJDDDDDDDY\n"
"        ,$Y**+Y+PPPPP++P**P+%JJJJJJJDJJJ*+%Y\n"
"        PDJD+YY$YYY+PPPP*P+Y*DJJJJJDDD%Y ,P*+,\n"
"        +P++PPPPP++YYYYP%P++*JJJJJJJ%+,   $+P$\n"
"              ,,,,,,$YY+P++Y+%*DJJD*,\n"
"                         ,,, , $++,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                       ,$$,\n"
"                                      YPPP+,\n"
"                                     ,*P+YY$\n"
"                             ,$YYY++PDD*P++P$\n"
"                           $+P%DDDDDDDJJDD%%Y\n"
"            Y*+$          $**%%JJDDDDJJJJJDD*\n"
"            $*%+Y$$$$,$$$$***JDJJJDDDJJJJDJD+\n"
"          ,$+*P+++YYYYY+++*PDJJJJJJDDDJJJJDY\n"
"         Y%DD*$$+P*P+++PP***DJJJJJJJDDDJJD%+,\n"
"         YPY,$YYYY++PP+P*%**DJJJJJJJJJJDP$YPP,\n"
"              ,$$Y++++PP*%*PDJJJJJJJJJ%$    $,\n"
"                  ,,$$YP**PPDDDJJJJJD*,\n"
"                      ,++Y,,Y$$Y+PP+$\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                         ,\n"
"                                       $+P+$\n"
"              $+Y,                    ,**P++,\n"
"              $*%+$,           ,,,$YP*%%P+YY$\n"
"              ,P*YYY,       $YP%%%DDDDDD*PPPP$\n"
"           ,+*D*+YYY$$,,,$$P*%%JDDDDDDJJJDDD*,\n"
"           +**++YPYYYYYYY$+%*DDJJJJDDDJJJJJD$\n"
"               Y+P*P+++P+Y***DJJJJJJDDJJJJJ*Y$,\n"
"                ,Y*****P++%P*JJJJJJJDDJJJDY+PP+,\n"
"                  Y+PP%%%%%**JJJJJJJJJJJ*,    ,,\n"
"                   ,$YP***%*%JJJJJJJJJJ*,\n"
"                        ,,$**++P%DJJ%PY,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                ,P+$\n"
"                ,+DP$$,\n"
"               ,$P*YYY,                 $YY$\n"
"             $*%D*Y$$$                 Y**PP$\n"
"             ,Y$++YY$$,      ,,,,,$Y++PD%PP+Y\n"
"                 $YYYY$,,,,$+**DD%DDDDJJ*P+YY$\n"
"                  YYYY$$$$+%%%DJDDDDDDDDD*PPPP$\n"
"                  Y*+YYYY$+D*%JJJJDDDDJJJJD%*$,\n"
"                  $%%*PP+Y+D*%JJJJJJDDJJJJJ%**PP+,\n"
"                   ,+*%+P+PDP%JJJJJJJDJJJJY ,YY$$,\n"
"                     ,$Y*DDD*%JJJJJJJJJJ%$\n"
"                        ,Y*D*%DJJJJJJJD+\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                  ,P+$,\n"
"                   +DPY$,\n"
"                $Y+*PYYY,\n"
"               ,P*%%Y$$$\n"
"                  ,Y$$$,\n"
"                   $$$$                  ,,,\n"
"                  ,$$Y$,               ,+PP+$\n"
"                  $Y$YY$, ,,YPPP*+PPP+P%%*PPP$\n"
"                  $+Y$$Y$$Y%%%DDDDDDDDJJ%**P+Y\n"
"                  ,$YYYYYY+D%%DJDDDDDDDJD*PPY+Y,\n"
"                    ,$+++Y+D%%JJJJDDDDDDJDPPPPP+,,\n"
"                      $+P++D%*JJJJJJJDJJJJD%P+***+,\n"
"                       ,$+*J%*JJJJJJJJJJJJ%P, $,,,\n"
"                          +J%%JJJJJJJJJJDY\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                    $,\n"
"                    Y%+$,\n"
"                 ,Y+PD*++$,\n"
"                 ,YP%*+Y+Y\n"
"                    $YYYY\n"
"                    $$$Y,\n"
"                   ,$$Y+$\n"
"                   $$$YY$,\n"
"                  ,YYYYYY$   ,,,           ,,\n"
"                  YYYYYYY$$YP**P+$$$,,,$Y++P*P,\n"
"                  $+YY$$$Y$%D%DDDDDDD%%%*PP+P*+\n"
"                   ,++YYYYY%DDJJDDDDDDJD%*P++PP$\n"
"                    $P+PPPPD%DJJJDDDDDJJD%**P+PY\n"
"                      ,YPPPJ%*JJJJDDDJJDD%**++PP,\n"
"                        ,,,Y*%JJJJJJJJJJJJ*PPP+PPY,\n"
"                           ,*%JJJJJJJJJJJ%%*++YYYY,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                      ,\n"
"                    ,,+$,\n"
"                    +*%P$,\n"
"                    Y*%*PY$\n"
"                     Y+++*Y\n"
"                     $++P+$\n"
"                    $YY+P+Y$\n"
"                   ,YY+,$P+Y,\n"
"                  ,YY+$ ,P+Y$, ,,\n"
"                  $+YY$$,++YY+P*%+,         ,$Y,\n"
"                  YP+Y$YY$$$P%**%DDP,  ,$,,+%%*P,\n"
"                  ,$+++YYYYY%%DDDDDD%**%*PP*DD%*Y\n"
"                     $Y+++YPDDJJDDDDDDD%*P++P%D*+\n"
"                       $***DD%JJDDDDDDJD*PP++P%*Y\n"
"                        $Y+P*%JJJJDDDJJDD%**P+PP+\n"
"                            YDJJJJJJJJJJD%**P+++P,\n"
"                           $*%DJJJJJJJJDJD*PP++P*+\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                      ,\n"
"                    ,,+$,\n"
"                    +*%P$,\n"
"                    Y*%*PY$\n"
"                     Y+++*Y\n"
"                     $++P+$\n"
"                    $YY+P+Y$\n"
"                   ,YY+,$P+Y,\n"
"                  ,YY+$ ,P+Y$, ,,\n"
"                  $+YY$$,++YY+P*%+,         ,$Y,\n"
"                  YP+YYYY$$$P%**%DDP,  ,$,,+%%*P,\n"
"                  ,$+++YYYYY%%DDDDDD%%*%*PP*DD%*Y\n"
"                     $Y+++YPDDJJDDDDDDD%*P++P%D*+\n"
"                       $***DD%JJJDDDDDJD*PP++P%*Y\n"
"                        $Y+P*%JJJDDDDJJDD%**P+PP+\n"
"                            YDJJJJJJJJJJD%**P+++P,\n"
"                           $*%DJJJJJJJJDJD*PP++P*+\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                        ,$,\n"
"                       $YY$\n"
"                      ,+$YY,\n"
"                      $%Y$PP,\n"
"                      $D*$+PY$\n"
"                      +D%P$YPY$\n"
"                     +P+P%PY*+Y$\n"
"                    ,PP*PY, PPY$,\n"
"                    $+PP,   ,+Y$$,\n"
"                   $PP*PY$,,,YYP*%*$\n"
"                  ,+**+++Y$$$+*%%DD%P,       $Y++,\n"
"                   ,+P++YYYYY%%**%DDD*Y$Y$,,PD%**+\n"
"                     ,,PP++Y+DDDDDDDDDDDD%*%DDDD%+\n"
"                       ,$+%*DDJJDDDDDD%**PPP*DDD%$\n"
"                         ,P*P%JJJDDDDJD*PP+++%P**,\n"
"                             *JJJDDDDJJD%PPPP+,*P,\n"
"                            $%JJJJJJJJJDD%**+++PP,\n"
"                           ,*%DJJJJJJJJJJ%*PP+++*+\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                             ,\n"
"                           ,YY$\n"
"                           ,YYY,\n"
"                            ,+Y,\n"
"                            ,P*+,\n"
"                     ,,,    ,%%+Y$\n"
"                     ,$$$,   ,$PPY$,\n"
"                     ,Y$$Y,    +*+Y$\n"
"                      Y%+$$$,  ,YY$$\n"
"                    ,+%JJDP$, ,$$$$Y,\n"
"                    +%%%%*+$,$$$YP%%P\n"
"                   ,*%%%P$$YY$Y*DDDDDP,        ,,\n"
"                    ,$+PP++YYYP%%DDDDD*,    ,$+PP$\n"
"                        ,$+++P%**%DDDDD%PY$$*DD**+\n"
"                           ,$*DDDDDDDDDDDDDDDDDD%P\n"
"                             *JJDDDDDD%%*P*%DDDD%Y\n"
"                            ,*JJJDDDDD%*PP++*D+**,\n"
"                             *JJJDDDJJD%PP++PPY**,\n"
"                            $%JJJJJJJJJD%***++PP*Y\n"
"                           ,*%%DJJJJJJJJD%**P++P**$\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                ,YY$\n"
"                                ,YY$\n"
"                                 YY$\n"
"                                 YPY\n"
"                                 *%+$\n"
"                                 Y**+$\n"
"                                  P%*+,\n"
"                                  +P+Y,\n"
"                                 ,$$$$,\n"
"                    ,$$YYYY,,,,,$$$$Y$,\n"
"                    ,YYY+YYY$$$$$YP*%%Y\n"
"                     ,$$YYYYYY$Y*%DDDD*,\n"
"                        ,,YPP+Y*DDDDDDD*,      ,,\n"
"                           ,+****%DDDDDD*$, ,P*PP$\n"
"                             Y%%%%DDDDDDDD%*%DD%%+\n"
"                             YDJJDDDDDDDDDDJDDDD%+\n"
"                             YDJJDDDDDD%***%DD%D%Y\n"
"                             YDJJJDDJJ%*PP++*D$P*$\n"
"                             YJJJJDJJJD*PP++PP$**$\n"
"                            $*DJJJJJJJJD%PP*++PP*+,\n"
"                           Y***%*P*%JJJJJD%*P+++*%$\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                     ,YY,\n"
"                                     $YY$\n"
"                                    ,YY+,\n"
"                                    ,*%+\n"
"                                    $D*Y,\n"
"                                    ,YPPY,\n"
"                                      +*+$\n"
"                                     ,**PY\n"
"                                    ,$YY$,\n"
"                       ,$$,,,,,,  ,,$$$$$,\n"
"                      ,Y++YY$$$$$$$$YYY$$,\n"
"                     $Y+P+++YY$$$Y+*%%%*$\n"
"                     $Y+++Y++++Y+%DDDDDD$\n"
"                      ,,,$$$$+*P%DDDDDDJ*\n"
"                              Y%DDDDDDDDDP,   ,$$,\n"
"                              ,***%DDDDDDD%P$PD%*P,\n"
"                              PD%DDDDDDDDDDDDDDD%%$\n"
"                             ,%JJDDDDDDDDDDDDDDDD*,\n"
"                             ,*JJJDDJDD%**P*%D%*%P,\n"
"                             ,*JJJJDJJJ%*P+++*YY%+\n"
"                             ,%JJJJJJJJD*PP++P+P*+\n"
"                            $*%%JJJJJJJJD****+++P*+\n"
"                           ,***YYY+DJJJJJJD%*P++P*Y\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                           ,\n"
"                                          $Y$\n"
"                                        ,$Y+Y\n"
"                                        $**Y,\n"
"                                        ,%%,\n"
"                                       ,P*+$\n"
"                                        ,P*Y,\n"
"                                         Y*+,\n"
"                                         +*P$\n"
"                                        $PP+,\n"
"                          ,,,,        ,$$$$$\n"
"                      $YY+++Y$$,,,,,,,$$$$$$\n"
"                      $Y++YY+YY$$$$$$YYYY$$,\n"
"                       ,,$Y++PP+YY+*%%%%%+$\n"
"                           ,,$+*+*DDDDDDD*,\n"
"                               Y*DJDDDDDJ%\n"
"                                $JJDDDDDDDP,\n"
"                               $+DDDDDDDDDD*+Y+P+Y,\n"
"                              ,**%%DDDDDDDDDDDDDD%+\n"
"                              YDDDDDDDDDDDDDDDDDD%P\n"
"                              $DJJDDDJDDD%**%DD%D%Y\n"
"                              $DJJJDDJJJ%*P++P*Y%*,\n"
"                              ,DJDJJJJJJ%*PP++PPPP,\n"
"                              +D%$DJJJJJJD*PPP++++,\n"
"                            ,P%**,$DJJJJ%*%D%%PPP*P,\n"
"                            $**$,  ,YY$$  ,YP*PPPP+\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                            ,,,$$,\n"
"                                            +P+++,\n"
"                                            +J%$\n"
"                                           ,YP+,\n"
"                                           Y*PY\n"
"                                            PPY,\n"
"                                           ,PPY,\n"
"                                           $*+Y$\n"
"                       $Y$$,               Y*P+$\n"
"                       $Y++$$$,          ,$+++Y,\n"
"                        $$Y+++Y,,       ,$Y$$Y,\n"
"                          ,$P*PY$$$$,,,$$Y$$$,\n"
"                             $+*+YYYYY+++Y$$$\n"
"                               Y*P+P%%DD%%*Y,\n"
"                                $**JDDDDDDDY\n"
"                                 $%JDDDDDDD$\n"
"                                  *JDDDDDDDP,\n"
"                                  *JDDDDDDDD%+Y+Y,\n"
"                               Y+P%JDDDDDDDDDDDDD%+,\n"
"                              ,*DDDDDDDDDDDDDDDDDD%$\n"
"                              ,%JJJDDDJDD%*PP*%DDD*,\n"
"                              ,%J%JJDDJJJ%*P+++P*%+\n"
"                              ,*J$$%JJJJJD*PPP+P+PY\n"
"                               *D$  $YPP*DJ%***++PY\n"
"                             ,+%DY       ,YP*%*PPPP,\n"
"                             Y**+Y           ,,$Y++,\n"
"                              ,,\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                                      Y+,\n"
"                                                     ,*J*Y,\n"
"                               ,,                   Y+Y+%%,\n"
"                               YPP$                ,+YY$ ,\n"
"                               ,P%Y$,             ,YYYY,\n"
"                                ,P*+Y,            $YYY$,\n"
"                                  +P+Y           $YYYY,\n"
"                                  ,PPY$,        Y+++Y,\n"
"                                   ,*P+Y,     ,$YYYY,\n"
"                                    ,PP++Y,,,$Y$$Y$\n"
"                                     ,P+YYYYYYYY$Y,\n"
"                                      Y+P*%%%*+YY$\n"
"                                      ,%JDDDDDDPY,\n"
"                                      $DDDDDJDDY\n"
"                                      PJDDDDDD%,\n"
"                                     ,%DDDDDDDD+,\n"
"                                     $DDDDDDDDDD%Y\n"
"                                    $%JDDDDD%%**%DP,\n"
"                                 ,Y*DJDDDJJD%*P++PD*,\n"
"                                $*DJJJJJDJJJD*PP++P*Y\n"
"                                PDJDDDDD%DJJJJ%**P+++\n"
"                                *%P,,,,, ,,$$+%%%P+PY\n"
"                               ,*%$            ,YPP+,\n"
"                                P*,              P*Y\n"
"                               $%P,             $%P\n"
"                               P%*,             $*P$\n"
"                              ,P%*$              YPY\n"
"                               ,$,\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                                        Y*$\n"
"                                  ,$,                 ,$PD*$\n"
"                                  PD+,                ++$PJ%\n"
"                                  ,PPY,              $Y$Y,$$\n"
"                                   ,P+Y,            ,YYY$\n"
"                                    $PY$,          $YYY$\n"
"                                     +PY$,        $+++Y,\n"
"                                     ,PP+Y,    ,$$YY++,\n"
"                                      ,*P++$,,$YY$$YY\n"
"                                       +PYYY+++Y$$$Y,\n"
"                                       $P*%%DD%%YYY,\n"
"                                       ,DDDDDDDDP+$\n"
"                                       $DDJDDDDD+$\n"
"                                       *DDDDDDDD,\n"
"                                      ,%DDDDDDDDP,\n"
"                                      YJDDDDDD%%%%Y\n"
"                                     YDDDDJDD%*P+P%Y\n"
"                                   $%JJJDDJJD%*P+++%Y\n"
"                                 ,+DJJJJJJJJJJD*PPP++,\n"
"                                ,*DJJJ%PP+P***DJD%P++$\n"
"                                +%%PY$        $YPPPP+,\n"
"                                $%*,             $**+\n"
"                                Y%P              $%*,\n"
"                                +%Y              P%Y\n"
"                                P%$             $%P\n"
"                               Y%*Y             +**+,\n"
"                              $PPPY             ,,,$,\n"
"                                 ,\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                                          YY,\n"
"                                     ,*+                ,$*%Y\n"
"                                     *%Y$              ,+YYD%$\n"
"                                     $PY$,            ,$$Y$PJY\n"
"                                      $PY$           ,$$$$, ,\n"
"                                       +Y$,        ,YYYY$,\n"
"                                       $P+Y,     ,,YYY+Y,\n"
"                                        P*P+$,,,$$$$Y+$\n"
"                                        $P++P***+$$$Y,\n"
"                                         +%DDDDDDPYY,\n"
"                                         *DDDDDDD*Y,\n"
"                                        ,DDDDDDDDP$\n"
"                                        *DDDDDDDD$\n"
"                                       $DDDDDDDDD*,\n"
"                                       *JDDDDD%*PP*Y\n"
"                                     ,PJDDDJJD%PP++*Y\n"
"                                    Y%JJJDJJJJD%PPPPP,\n"
"                                   YDJJJJDDJJJJJD%*++Y\n"
"                                  Y%DJJ*$,,$YYYP*%*PPY\n"
"                                 Y%%%P$          $P**,\n"
"                                 *%*$             %%*,\n"
"                                ,%%P             ,%%+\n"
"                                +%*,             Y%P,\n"
"                                P%+              P*$\n"
"                                *%Y             +%P,\n"
"                              ,+%*P,            $YPP,\n"
"                              ,+++Y,              ,,,\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                         ,$,               $$\n"
"                                        YP+$             ,$+%$\n"
"                                       ,%+$$           ,,$$+D*,\n"
"                                        $+$$         ,,$$$$Y%J$\n"
"                                         YY$,     ,,$YYYY$, ,$\n"
"                                         PP+$,,,$$$$$$++,\n"
"                                         +P+**%%%P$$$$Y,\n"
"                                         ,%DDDDDDD+YY,\n"
"                                         ,DDDJDDJDPY,\n"
"                                         +DDDDDDDD+,\n"
"                                        ,%DDDDDDDD$\n"
"                                        PDDDDD%**PP$\n"
"                                       +DDDDDJ%*P+++,\n"
"                                      YJJDDJJJJD*PPP+,\n"
"                                     YJJJJJJJJJJD%%P+Y\n"
"                                    ,%JJJ*++**P*D%*P++,\n"
"                                    PDDDY       ,$*PPY\n"
"                                   +%%*$          *D%,\n"
"                                  $%%P,           *D*,\n"
"                                 ,*%*,            %DP\n"
"                                 PD*,            ,%%$\n"
"                                ,%%Y             +%+\n"
"                                +D*,            $%P\n"
"                               ,*%P,           ,*%P$\n"
"                              $****$            Y+P+,\n"
"                              ,YYY$\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                                            ,\n"
"                                           ,$$           ,,$PY\n"
"                                          $+$$        ,,$$$Y**,\n"
"                                          $Y$$,$$,,,$$$YYY$$*@+\n"
"                                          $P*%%%%%+$$$YPY,  ,*$\n"
"                                          YDDDDDDD*YYYY$\n"
"                                          PDDDDDDJ*Y$,\n"
"                                         $%DDDDDDDP\n"
"                                        ,*DDDDD%**+,\n"
"                                        +DDDDDD%*P+Y,\n"
"                                       $DDDDJJJDD*PP+$\n"
"                                      ,%JJJJJJJJJDD%++$\n"
"                                      *JJJJDJJJDDD*P+++\n"
"                                     ,%DJD$,$$$,,Y%*P+,\n"
"                                     YD%%$       ,DDDY\n"
"                                     *%%+        ,DD*,\n"
"                                    +%*Y         ,DDP\n"
"                                   Y%%P          $DD+\n"
"                                  Y%%*,          YD%,\n"
"                                 ,%%P,           PD+\n"
"                                 +%*,           ,%*,\n"
"                                Y**+           ,P*+\n"
"                              $P***Y           $%**$\n"
"                              Y*P*P,            ,$Y,\n"
"                                 ,,\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                              ,$$$   ,,,,,,,,\n"
"                                           ,+*%DD%P$$$$$$$$YP,\n"
"                                          $%DDDDDJ%$$$Y+Y+YPD+\n"
"                                          +DDDDDDDD+YY++$, $D%,\n"
"                                         ,%DDDD%%**P$       $$\n"
"                                         *DDDDDD*P++Y,\n"
"                                        +JDDDJJJD%PPP$\n"
"                                       $DJJDJJJJJJDDP+$\n"
"                                       *JJJJJJJJJJ%*P++,\n"
"                                      ,%JJDPPPP+Y+D*PP$\n"
"                                      Y%%D$      ,DJD+\n"
"                                      +%*+       $D%*,\n"
"                                     ,%*P,       YD%+\n"
"                                     P%*,        +D%$\n"
"                                    Y%%+         *D*,\n"
"                                    *%*,         %D+\n"
"                                   $%*Y         ,%*,\n"
"                                   Y%P          +%Y\n"
"                                 ,+P*Y         +**$\n"
"                                +*%%*,         P%*Y\n"
"                               Y*%%P,          $P*+\n"
"                              ,YY+$              ,,\n"
"\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                               ,,,\n"
"                                            $P*%%*$\n"
"                                           +DDDDDJ*$$,,\n"
"                                          $DDDDD%%*Y$$Y$$$,,\n"
"                                         $%DDDDD%PP+Y+P++PPP,\n"
"                                        ,%DDDDJDD%PP++Y,,$*J+\n"
"                                        PJDDJJJJJJD%*+,   $DP\n"
"                                       $JJJJJJJJJJ%%P++,   $,\n"
"                                       PJJJJJJJJDD%P++Y,\n"
"                                      ,*DJ*,,$$$,,%JDP\n"
"                                      +%**,       %%%+\n"
"                                      *%*+       ,%%%$\n"
"                                     $D*P,       ,D%+\n"
"                                     $%*Y        YD*$\n"
"                                     +%*$        *D*,\n"
"                                     P%P,       ,%%$\n"
"                                     P%Y        +%Y\n"
"                                     P*$      ,+%P\n"
"                                   ,Y**$      P%%Y\n"
"                                  ,P%%*$      $%%Y\n"
"                                  ,+*Y,       $*P,\n"
"                                    ,         ,,,\n"
"\n"
"\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                               ,,,\n"
"                                            $P*%%*$\n"
"                                           +DDDDDJ*$$,,\n"
"                                          $DDDDD%%*Y$$Y$$$,,\n"
"                                         $%DDDDD%PP+Y+P++PPP,\n"
"                                        ,%DDDDJJD%PP++Y,,$*J+\n"
"                                        PJDDJJJJJJD%*+,   $DP\n"
"                                       $JJJJJJJJJJ%%P++,   $,\n"
"                                       PJJJJJJJJDD%P++Y,\n"
"                                      ,*DJ*,,$$$,,%JDP\n"
"                                      +%**,       %%%+\n"
"                                      ***+       ,%%%$\n"
"                                     $D*P,       ,D%+\n"
"                                     $%*Y        YD*$\n"
"                                     +%*$        *D*,\n"
"                                     P%P,       ,%%$\n"
"                                     P%Y        +%Y\n"
"                                     P*$      ,+%P\n"
"                                   ,Y**$      P%%Y\n"
"                                  ,P%%*$      $%%Y\n"
"                                  ,+*Y,       $*P,\n"
"                                    ,         ,,,\n"
"\n"
"\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                             $Y++$\n"
"                                           $*DDDD%$\n"
"                                          ,%DDDD%*+$,\n"
"                                         $%DDDDD%P++Y,,\n"
"                                        YDDDDJJJDD**P+Y$,\n"
"                                       ,DJJDJJJJJDDDP++++$\n"
"                                       *JJJJJJJJJD*P+++*%*,\n"
"                                      $DJJJJJJJJDDD%*P$,+JP\n"
"                                      +%%D+$,$YY,,%JJP  ,*P\n"
"                                      P%*P        *D%+   ,\n"
"                                     ,**%Y        *D%+\n"
"                                     ,D**$        *D*$\n"
"                                     $D*+        Y%%P,\n"
"                                      *%+       ,*%P,\n"
"                                      Y%+       +*+,\n"
"                                      ,*P,    ,+*+\n"
"                                      ,**Y   ,P*P,\n"
"                                      +%*+    +*P,\n"
"                                    ,+*D*$    $P+\n"
"                                    ,$$$,      ,\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n""\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"                                            ,Y++$,\n"
"                                           P%DD%*P+$\n"
"                                         $*DDDDD%P++$\n"
"                                        +DDJJJJJJD%*+,\n"
"                                       +JJDJJJJJJD%*+Y,\n"
"                                      YJJJJJJJJJJDP+++$\n"
"                                      *JJJJJJJJJJJJ%%*Y,\n"
"                                     ,%DD%+++*J%+$%@J%*Y\n"
"                                     YD%%$    P*Y PD%*%%$\n"
"                                     +D*Y     +J$ YJ%*PJP\n"
"                                     YD*Y     Y+  Y%*+$*$\n"
"                                      +%P,       $***,\n"
"                                       P*$      ,P*+,\n"
"                                       $%P,   ,YPPY\n"
"                                        +%+, ,**P$\n"
"                                        P%*Y ,+*P,\n"
"                                       ,*DD$   $$\n"
"                                        ,Y$\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
};


const char* breakdancegifanim(){
    static int anim_frame = 0;
    const char* ret = breakdancegif[anim_frame];
    anim_frame++;
    if(anim_frame == 37){anim_frame = 0;}
    return ret;
}
